{
  "name": "Create a content attachment",
  "enabledForApps": true,
  "method": "POST",
  "path": "/content_references/:content_reference_id/attachments",
  "previews": [
    {
      "name": "corsair",
      "description": "**Note:** To access the Content Attachments API during the preview period, you must provide a custom [media type](https://developer.github.com/enterprise/2.17/v3/media) in the `Accept` header:\n\n```\napplication/vnd.github.corsair-preview+json\n\n```",
      "required": true
    }
  ],
  "params": [
    {
      "name": "content_reference_id",
      "type": "integer",
      "required": true,
      "description": "",
      "location": "url"
    },
    {
      "name": "title",
      "type": "string",
      "description": "The title of the content attachment displayed in the body or comment of an issue or pull request.",
      "required": true,
      "location": "body"
    },
    {
      "name": "body",
      "type": "string",
      "description": "The body text of the content attachment displayed in the body or comment of an issue or pull request. This parameter supports markdown.",
      "required": true,
      "location": "body"
    }
  ],
  "requests": [
    {
      "title": "[A-1234] Error found in core/models.py file",
      "body": "You have used an email that already exists for the user_email_uniq field.\n ## DETAILS:\n\nThe (email)=(Octocat@github.com) already exists.\n\n The error was found in core/models.py in get_or_create_user at line 62.\n\nself.save()"
    }
  ],
  "description": "Creates an attachment under a content reference URL in the body or comment of an issue or pull request. Use the `id` of the content reference from the [`content_reference` event](https://developer.github.com/enterprise/2.17/v3/activity/events/types/#contentreferenceevent) to create an attachment.\n\nThe app must create a content attachment within six hours of the content reference URL being posted. See \"[Using content attachments](https://developer.github.com/enterprise/2.17/apps/using-content-attachments/)\" for details about content attachments.\n\nYou must use an [installation access token](https://developer.github.com/enterprise/2.17/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-an-installation) to access this endpoint.\n\nThis example creates a content attachment for the domain `https://errors.ai/`.",
  "responses": [
    {
      "headers": {
        "status": "200 OK",
        "content-type": "application/json; charset=utf-8"
      },
      "body": {
        "id": 101,
        "title": "[A-1234] Error found in core/models.py file'",
        "body": "You have used an email that already exists for the user_email_uniq field.\n ## DETAILS:\n\nThe (email)=(Octocat@github.com) already exists.\n\n The error was found in core/models.py in get_or_create_user at line 62.\n\n self.save()"
      }
    }
  ],
  "idName": "create-content-attachment",
  "documentationUrl": "https://developer.github.com/enterprise/2.17/v3/apps/installations/#create-a-content-attachment"
}
